### ISSUE TITLE
RFC: Time proposal

### ISSUE THREAD

**Issue by izuzu-izuzu** [Sentalang/core#1]
---
title: Sentalang time proposal
author: Izuzu
original_date: 2022-12-22
last_updated: 2023-01-11
comment: This update includes step-by-step solutions to the offset correctness test.
---

## Time

Sentalang uses musical time (in beats) rather than actual time (in seconds or milliseconds) to mark the temporal location of an event (such as a "tap" note, or a BPM change). This means that to convert an event's musical time to its actual time, you only need to use all prior BPM and offset declarations, and current offset declaration.

To specify the onset (start) of an event or its duration (in beats), use the provided Sentalang number format.

```
// 10 whole beats
[10]
[10, 0, 1]

// 3.5 beats
[3, 1, 2]

// (25 + 2/3) beats, or 25.666... beats
[25, 2, 3]
```

Here's an example of converting musical time (in beats) to actual time (in seconds).

```
// Suppose that BPM remains constant at 200 throughout.

// There is a "tap" note at (125 + 1/3), or 125.333... beats.
[125, 1, 3]

// (125 + 1/3) beats
// = (125 + 1/3) * (60 / 200)
// = 37.6 seconds
```

### A note on time signatures

Time signatures are still accepted by the Sentalang format; however, they're only used for notational purposes. Support for time signatures is dependent on game mode.

### BPM

To demonstrate how an event is declared in Sentalang, we'll start with how to declare a BPM event. The snippet below contains 2 such BPM events.

```json
[
    // 1st BPM event: initial BPM of 230
    {
        "kind": "BPM",
        "beat": [0],
        "value": 230.0
    },

    // ...
    // other notes and events
    // ...

    // 2nd BPM event: BPM changes to 180 at beat 72.5
    {
        "kind": "BPM",
        "beat": [72, 1, 2],
        "value": 180.0
    },

    // ...
    // more notes and events
    // ...
]
```

This example shows an example chart with an initial BPM of 230; then, at beat 72.5, the BPM changes from 230 to 180. It also shows the general pattern of how notes and events are declared.

#### Restrictions

- The value of a BPM declaration must be a strictly positive, finite number.
- No events should occur earlier (in terms of musical time) than the earliest BPM declaration.
- The earliest BPM declaration must be on beat 0.

### Offset

Sometimes a piece of music may not fully follow regular, evenly spaced beats. When this happens, the music and the chart may go out of sync with each other.

There're several possible reasons:

- The music is from a live performance, an orchestral recording, or an old recording, without the presence of a metronome or beat counter.
- The music is mixed from improperly cut sources (e.g., fan-made short versions of songs, song medleys).
- The music is deliberately made and performed such that it doesn't conform to regular beats (e.g., improvisational jazz, progressive rock).

In such cases, defining an offset in the middle of the track can bring the music and the chart back in sync.

> ***Applying offsets should be considered a last resort, as applying too many offsets is a symptom of declaring the wrong BPM or missing a BPM change.***

For compatibility with most existing rhythm games and notational software, Sentalang offers 2 kinds of offsets:

- **Instant** offsets (found in osu!, MuseScore, etc.): Best used for timing starts and ends of audio segments (e.g., songs within a song medley), or for timing deliberate pauses by the music performer.
- **Gradual** offsets: Best used for timing live performances, or for quick tempo swings in improvisational or free-style music.

#### Instant offset

An instant offset moves all events at or after the offset declaration (in musical time) by the same number of seconds.

Here's an example:

```json
[
    {"kind": "BPM", "beat": [0], "value": 120},                        // let's label this "event 1"
    {"kind": "TAP", "beat": [0]},                                      // event 2
    {"kind": "TAP", "beat": [1]},                                      // event 3
    {"kind": "TAP", "beat": [1, 1, 2]},                                // event 4
    {"kind": "OFFSET", "type": "INSTANT", "beat": [2], "value": 0.2},  // event 5
    {"kind": "TAP", "beat": [2]},                                      // event 6
    {"kind": "TAP", "beat": [3]}                                       // event 7
]
```

In the middle, you can see an instant offset declaration on beat 2, with a value of 0.2 seconds.

Since the instant offset affects all events at or after the beat on which the offset is declared, all events from beat 2 onward are moved by +0.2 seconds. In other words, events 6 and 7 occur 0.2 seconds later than they would without the offset.

Here's when each of the tap notes above occurs, in seconds:

| Event | Calculation          | Time (in seconds) |
|-------|----------------------|-------------------|
| 2     | 0 * (60 / 120)       | 0                 |
| 3     | 1 * (60 / 120)       | 0.5               |
| 4     | 1.5 * (60 / 120)     | 0.75              |
| 6     | 2 * (60 / 120) + 0.2 | 1.2               |
| 7     | 3 * (60 / 120) + 0.2 | 1.7               |

#### Gradual offset

A gradual offset works as follows:

1. Suppose a gradual offset is declared on beat `n`, with value `t` seconds.

2. All events before or at beat `n - 1` remain unaffected.

3. All events at or after beat `n` are moved by `t` seconds (similar to an instant offset).

4. All events between beats `n - 1` and `n` are moved by fractions of `t` seconds, proportional to how many beats they are away from beat `n - 1`.

    To put simply, an event 1/4 beats after beat `n - 1` receives 1/4 the offset value (i.e., it is moved by `t/4` seconds); an event halfway between beat `n - 1` and beat `n` receives half the offset value (i.e., it is moved by `t/2` seconds).

    The exact formula for the offset received by an event at beat `m`, where `n - 1 < m < n`, is

    `offset = (m - (n - 1)) * t`

Gradual offsets can be considered a "smoother, more delicate" counterpart to instant offsets. In addition to moving all events at or after the offset declaration by the same number of seconds, a gradual offset also lightly nudges events within the preceding 1-beat interval, so that the application of the offset feels smoother and more gradual (hence the name).

Here's an example, similar to the instant offset example in the previous subsection:

```json
[
    {"kind": "BPM", "beat": [0], "value": 120},                        // let's label this "event 1"
    {"kind": "TAP", "beat": [0]},                                      // event 2
    {"kind": "TAP", "beat": [1]},                                      // event 3
    {"kind": "TAP", "beat": [1, 1, 2]},                                // event 4
    {"kind": "OFFSET", "type": "GRADUAL", "beat": [2], "value": 0.2},  // event 5
    {"kind": "TAP", "beat": [2]},                                      // event 6
    {"kind": "TAP", "beat": [3]}                                       // event 7
]
```

- Events 6 and 7 receive the full offset value of +0.2 s.

- Event 3 lies at the beginning of the preceding 1-beat interval, so it receives no offset.

- Event 4 lies exactly at the midpoint of the preceding 1-beat interval, so it receives half the offset value (i.e., it is moved by +0.1 s).

Here's when each of the tap notes above occurs, in seconds:

| Event | Calculation                              | Time (in seconds) |
|-------|------------------------------------------|-------------------|
| 2     | 0 * (60 / 120)                           | 0                 |
| 3     | 1 * (60 / 120)                           | 0.5               |
| 4     | 1.5 * (60 / 120) + (1.5 - (2 - 1)) * 0.2 | 0.85              |
| 6     | 2 * (60 / 120) + 0.2                     | 1.2               |
| 7     | 3 * (60 / 120) + 0.2                     | 1.7               |

#### Restrictions

- No two offset events should overlap.

    Overlapping includes:

    - Two instant offsets on the same beat
    - An instant offset less than 1 beat before a gradual offset
    - Two gradual offsets less than 1 beat away from each other

- Offsets should not change the temporal order of events in musical time or in actual time.

    More concretely, if event A is assigned a musical time less than event B, then event A should occur earlier than event B in actual time as well, even after all offsets are applied.

#### Complex example and correctness tests

```json
[
    {
        "kind": "BPM",
        "beat": [0],
        "value": 180.0
    },
    {
        "kind": "OFFSET",
        "type": "INSTANT",
        "beat": [0],
        "value": 0.2
    },
    {
        "kind": "HOLD",
        "beat": [28, 3, 4],
        "duration": [1, 1, 4]
        // other hold note data
    },
    {
        "kind": "TAP",
        "beat": [29, 1, 4]
        // other tap note data
    },
    {
        "kind": "OFFSET",
        "type": "GRADUAL",
        "beat": [30],
        "value": 0.08
    },
    {
        "kind": "BPM",
        "beat": [48],
        "value": 200.0
    },
    {
        "kind": "TAP",
        "beat": [50]
        // other tap note data
    },
    // ...
    // remaining notes and events
    // ...
]
```

##### Questions

1. When, in seconds, does the hold note start?

2. How long, in seconds, does the hold note last?

3. When, in seconds, does the 1st tap note occur?

4. When, in seconds, does the BPM change from 180 to 200?

5. When, in seconds, does the 2nd tap note occur?

##### Hint

For events with "duration" (such as hold notes), you can and should treat its start and end as two separate events for timing purposes.

##### Answers

1. **9.78333… seconds** (or in fractional form, `[9, 47, 60]`)

    The start of the hold note is at beat 28.75.

    Beat 28.75 is affected by the following timing events that precede it:
    - BPM = 180 at beat 0
    - Instant offset = 0.2 s at beat 0

    Time to reach beat 28.75 without offset:
        28.75 * (60/180) = 9.58333… seconds

    Instant offset received:
        0.2 seconds

    Total time to reach beat 28.75:
        9.58333… + 0.2 = **9.78333… seconds**

2. **0.49666… seconds** (or `[0, 149, 300]`)

    The hold note has a duration of 1.25 beats, so the end of the hold note is at beat 28.75 + 1.25 = 30.

    Beat 30 is affected by the following timing events that precede it:
    - BPM = 180 at beat 0
    - Instant offset = 0.2 s at beat 0
    - Gradual offset = 0.08 s at beat 30

    Time to reach beat 30 without offsets:
        30 * (60 / 180) = 10 seconds

    Instant offset received:
        0.2 seconds

    Gradual offset received:
        (30 - (30 - 1)) * 0.08 = 0.08 seconds

    Total time to reach beat 30:
        10 + 0.2 + 0.08 = 10.28 seconds

    Duration (in seconds) of the hold note:
        10.28 - 9.78333… = **0.49666… seconds**

3. **9.97 seconds** (or `[9, 97, 100]`)

    The first tap note occurs at beat 29.25.

    Beat 29.25 is affected by the following timing events that precede it:
    - BPM = 180 at beat 0
    - Instant offset = 0.2 s at beat 0
    - Gradual offset = 0.08 s at beat 30, which also affects the interval between beat 29 and beat 30

    Time to reach beat 29.25 without offsets:
        29.25 * (60 / 180) = 9.75 seconds

    Instant offset received:
        0.2 seconds

    Gradual offset received:
        (29.25 - (30 - 1)) * 0.08 = 0.02 seconds

    Total time to reach beat 29.25:
        9.75 + 0.2 + 0.02 = **9.97 seconds**

4. **16.28 seconds** (or `[16, 7, 25]`)

    The BPM change occurs at beat 48.

    Beat 48 is affected by the following timing events that precede it:
    - BPM = 180 at beat 0
    - Instant offset = 0.2 s at beat 0
    - Gradual offset = 0.08 s at beat 30

    Time to reach beat 48 without offsets:
        48 * (60 / 180) = 16 seconds

    Instant offset received:
        0.2 seconds

    Gradual offset received:
        0.08 seconds

    Total time to reach beat 48:
        16 + 0.2 + 0.08 = **16.28 seconds**

5. **16.88 seconds** (or `[16, 22, 25]`)

    The second tap note occurs at beat 50.

    Beat 50 is affected by the following timing events that precede it:
    - BPM = 180 at beat 0
    - BPM = 200 at beat 48
    - Instant offset = 0.2 s at beat 0
    - Gradual offset = 0.08 s at beat 30

    Time to reach beat 48 without offsets:
        48 * (60 / 180) = 16 seconds

    Time to go from beat 48 to beat 50 without offsets:
        (50 - 48) * (60 / 200) = 0.6 seconds

    Instant offset received:
        0.2 seconds

    Gradual offset received:
        0.08 seconds

    Total time to reach beat 50:
        16 + 0.6 + 0.2 + 0.08 = **16.88 seconds**

**Comment by donmai-me** [comment]
Pinging @Sentalang/core-specification members for comments.

Since this mainly focuses on offsets, I'll first focus on those. I think the names **gradual** and **instant** offset needs a bit more work. But first let's talk about my thoughts on the two types of offsets.

Those two types can be thought of as *displacing* and *non-displacing*. Gradual being displacing, and instant being non-displacing. As gradual offset moves/displaces the notes from their (temporal) position, while instant does not.

With this in mind I think we can "unify" the computation for the two of them as just BPM changes with the added step for instant offsets to compensate for the "drag". Thoughts?

**Comment by izuzu-izuzu** [comment]
I don’t fully understand the *displacing* distinction between the two types of offsets.

- Neither type of offsets changes the musical time (in beats) of events – a note at beat 30 remains at beat 30 no matter what offsets apply to it.
- Both types of offsets change a note's actual time (in seconds).

@donmai-me, can you clarify and/or give an example that illustrates this distinction? Thanks.

Regarding unification, the computations required to calculate a note's actual time after offsets are applied are so simple that I don’t think we need to worry much about it. Different implementations of Sentalang may have different methods of calculation, but as long as they pass the correctness test above, it should be fine.

**Comment by donmai-me** [comment]
Gradual offsets changes the timing of events before and upto the offset beat. See step 4 of gradual offset computation. Instant offset meanwhile does not change the timing of any event before and upto the offset. Yes it does not change the declared beat but its computation to seconds does change. 

I'll update this later with sample computations so you can clearly see what I mean.

**Comment by donmai-me** [comment]
Let's use one of your examples. For gradual:

```json
[
    {"kind": "BPM", "beat": [0], "value": 120},                        // let's label this "event 1"
    {"kind": "TAP", "beat": [0]},                                      // event 2
    {"kind": "TAP", "beat": [1]},                                      // event 3
    {"kind": "TAP", "beat": [1, 1, 2]},                                // event 4
    {"kind": "OFFSET", "type": "GRADUAL", "beat": [2], "value": 0.2},  // event 5
    {"kind": "TAP", "beat": [2]},                                      // event 6
    {"kind": "TAP", "beat": [3]}                                       // event 7
]
```

Events 6 and 7 are moved by 0.2 seconds forward; event 5 is still on the same time. Event 4 is moved by 0.1 seconds since it's 1/2 beats away from beat 1.

Same example but replacing gradual with instant:

```json
[
    {"kind": "BPM", "beat": [0], "value": 120},                        // let's label this "event 1"
    {"kind": "TAP", "beat": [0]},                                      // event 2
    {"kind": "TAP", "beat": [1]},                                      // event 3
    {"kind": "TAP", "beat": [1, 1, 2]},                                // event 4
    {"kind": "OFFSET", "type": "INSTANT", "beat": [2], "value": 0.2},  // event 5
    {"kind": "TAP", "beat": [2]},                                      // event 6
    {"kind": "TAP", "beat": [3]}                                       // event 7
]
```

Only events 6 and 7 are moved by 0.2 seconds. All events prior to beat 2 doesn't get any offset.

This is what I mean by displacing: `gradual` offset at beat `n` displaces events that are in the range `(n-1, n]` and events after it; while `instant` offset only displaces events after beat `n`. Hope that makes it clear

**Comment by izuzu-izuzu** [comment]
We can work on the exact names for these types of offsets later in another issue thread. For now, let's close this one and provisionally include both.
